### ISSUE TITLE
 Type error: Return value of FireflyIII\Support\Steam::balance() must be of the type string, float returned

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#225]
Got this error after a painful php7 + nginx update.

```
[2016-03-20 10:57:34] production.DEBUG: You are at index.  
[2016-03-20 15:34:20] production.DEBUG: In mail job constructor for error handler.  
[2016-03-20 15:34:20] production.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","errorMessage":"Type error: Return value of FireflyIII\\Support\\Steam::balance() must be of the type string, float returned","time":"Sun, 20 Mar 2016 15:34:20 +0000","stackTrace":"#0 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(6220): FireflyIII\\Support\\Steam->balance(Object(FireflyIII\\Models\\Account), Object(Carbon\\Carbon))\n#1 \/var\/www\/domain\/htdocs\/firefly-iii\/app\/Repositories\/Account\/AccountRepository.php(298): Illuminate\\Support\\Facades\\Facade::__callStatic('balance', Array)\n#2 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(12370): FireflyIII\\Repositories\\Account\\AccountRepository->FireflyIII\\Repositories\\Account\\{closure}(Object(FireflyIII\\Models\\Account), 0)\n#3 \/var\/www\/domain\/htdocs\/firefly-iii\/app\/Repositories\/Account\/AccountRepository.php(318): Illuminate\\Support\\Collection->each(Object(Closure))\n#4 \/var\/www\/domain\/htdocs\/firefly-iii\/app\/Http\/Controllers\/HomeController.php(111): FireflyIII\\Repositories\\Account\\AccountRepository->getSavingsAccounts()\n#5 [internal function]: FireflyIII\\Http\\Controllers\\HomeController->index(Object(FireflyIII\\Repositories\\Account\\AccountRepository))\n#6 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9268): call_user_func_array(Array, Array)\n#7 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9330): Illuminate\\Routing\\Controller->callAction('index', Array)\n#8 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9310): Illuminate\\Routing\\ControllerDispatcher->call(Object(FireflyIII\\Http\\Controllers\\HomeController), Object(Illuminate\\Routing\\Route), 'index')\n#9 [internal function]: Illuminate\\Routing\\ControllerDispatcher->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#10 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#11 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#12 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9787): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#13 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9311): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#14 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9298): Illuminate\\Routing\\ControllerDispatcher->callWithinStack(Object(FireflyIII\\Http\\Controllers\\HomeController), Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'index')\n#15 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(8385): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request), 'FireflyIII\\\\Http...', 'index')\n#16 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(8372): Illuminate\\Routing\\Route->runController(Object(Illuminate\\Http\\Request))\n#17 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(8086): Illuminate\\Routing\\Route->run(Object(Illuminate\\Http\\Request))\n#18 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#19 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#20 \/var\/www\/domain\/htdocs\/firefly-iii\/app\/Http\/Middleware\/Binder.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#21 [internal function]: FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#22 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#23 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#24 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#25 \/var\/www\/domain\/htdocs\/firefly-iii\/app\/Http\/Middleware\/Range.php(90): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#26 [internal function]: FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#27 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#28 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#29 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#30 \/var\/www\/domain\/htdocs\/firefly-iii\/app\/Http\/Middleware\/AuthenticateTwoFactor.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#31 [internal function]: FireflyIII\\Http\\Middleware\\AuthenticateTwoFactor->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#32 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#33 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#34 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#35 \/var\/www\/domain\/htdocs\/firefly-iii\/app\/Http\/Middleware\/Authenticate.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#36 [internal function]: FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#37 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#38 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#39 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#40 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(3165): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#41 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#42 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#43 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#44 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#45 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(13221): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#46 [internal function]: Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#47 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#48 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#49 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#50 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(11781): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#51 [internal function]: Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#52 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#53 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#54 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#55 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(12960): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#56 [internal function]: Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#57 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#58 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#59 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#60 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(12897): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#61 [internal function]: Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#62 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#63 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#64 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#65 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#66 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9787): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#67 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(8087): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#68 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(8078): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#69 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(8068): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#70 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(2393): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#71 [internal function]: Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))\n#72 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#73 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(3226): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#74 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#75 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9797): call_user_func_array(Array, Array)\n#76 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#77 \/var\/www\/domain\/htdocs\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#78 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#79 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(9787): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))\n#80 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(2340): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#81 \/var\/www\/domain\/htdocs\/firefly-iii\/bootstrap\/cache\/compiled.php(2324): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))\n#82 \/var\/www\/domain\/htdocs\/firefly-iii\/public\/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#83 {main}","file":"\/var\/www\/domain\/htdocs\/firefly-iii\/app\/Support\/Steam.php","line":38,"code":0}  
[2016-03-20 15:34:20] production.DEBUG: Start of handle()  
[2016-03-20 15:34:20] production.ERROR: Swift Transport ExceptionConnection could not be established with host smtp [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]  
[2016-03-20 15:34:20] production.DEBUG: Successfully handled error.  
[2016-03-20 15:34:20] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of FireflyIII\Support\Steam::balance() must be of the type string, float returned in /var/www/domain/htdocs/firefly-iii/app/Support/Steam.php:38
Stack trace:
#0 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(6220): FireflyIII\Support\Steam->balance(Object(FireflyIII\Models\Account), Object(Carbon\Carbon))
#1 /var/www/domain/htdocs/firefly-iii/app/Repositories/Account/AccountRepository.php(298): Illuminate\Support\Facades\Facade::__callStatic('balance', Array)
#2 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(12370): FireflyIII\Repositories\Account\AccountRepository->FireflyIII\Repositories\Account\{closure}(Object(FireflyIII\Models\Account), 0)
#3 /var/www/domain/htdocs/firefly-iii/app/Repositories/Account/AccountRepository.php(318): Illuminate\Support\Collection->each(Object(Closure))
#4 /var/www/domain/htdocs/firefly-iii/app/Http/Controllers/HomeController.php(111): FireflyIII\Repositories\Account\AccountRepository->getSavingsAccounts()
#5 [internal function]: FireflyIII\Http\Controllers\HomeController->index(Object(FireflyIII\Repositories\Account\AccountRepository))
#6 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9268): call_user_func_array(Array, Array)
#7 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9330): Illuminate\Routing\Controller->callAction('index', Array)
#8 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9310): Illuminate\Routing\ControllerDispatcher->call(Object(FireflyIII\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), 'index')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9787): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9311): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9298): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(FireflyIII\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#15 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(8385): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'FireflyIII\\Http...', 'index')
#16 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(8372): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#17 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(8086): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/domain/htdocs/firefly-iii/app/Http/Middleware/Binder.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /var/www/domain/htdocs/firefly-iii/app/Http/Middleware/Range.php(90): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/domain/htdocs/firefly-iii/app/Http/Middleware/AuthenticateTwoFactor.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /var/www/domain/htdocs/firefly-iii/app/Http/Middleware/Authenticate.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(3165): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(13221): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(11781): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(12960): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(12897): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9787): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(8087): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(8078): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#69 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(8068): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#70 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(2393): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#72 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(3226): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9797): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /var/www/domain/htdocs/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(9787): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#80 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(2340): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#81 /var/www/domain/htdocs/firefly-iii/bootstrap/cache/compiled.php(2324): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#82 /var/www/domain/htdocs/firefly-iii/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#83 {main}  
```
Any idea?

**Comment by JC5** [comment]
On the command line:

``php artisan ca:cl``

Should do the trick.

**Comment by xzaz** [comment]
+1
