### ISSUE TITLE
Error when deleting asset account

### ISSUE THREAD

**Issue by StevenReitsma** [JC5/firefly-iii#273]
I'm getting a 'whoops'-error when deleting an asset/expense account. Works fine for revenue accounts. Stacktrace shown below.
There are no transactions linked to the account.

```
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`firefly`.`transactions`, CONSTRAINT `transactions_account_id_foreign` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE) (SQL: update `transactions` set `account_id` =  where `account_id` = 4) in /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:680
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(636): Illuminate\Database\Connection->runQueryCallback('update `transac...', Array, Object(Closure))
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(434): Illuminate\Database\Connection->run('update `transac...', Array, Object(Closure))
#2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(377): Illuminate\Database\Connection->affectingStatement('update `transac...', Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2033): Illuminate\Database\Connection->update('update `transac...', Array)
#4 /var/www/app/Crud/Account/AccountCrud.php(59): Illuminate\Database\Query\Builder->update(Array)
#5 /var/www/app/Http/Controllers/AccountController.php(107): FireflyIII\Crud\Account\AccountCrud->destroy(Object(FireflyIII\Models\Account), Object(FireflyIII\Models\Account))
#6 [internal function]: FireflyIII\Http\Controllers\AccountController->destroy(Object(FireflyIII\Crud\Account\AccountCrud), Object(FireflyIII\Models\Account))
#7 /var/www/bootstrap/cache/compiled.php(9370): call_user_func_array(Array, Array)
#8 /var/www/bootstrap/cache/compiled.php(9432): Illuminate\Routing\Controller->callAction('destroy', Array)
#9 /var/www/bootstrap/cache/compiled.php(9412): Illuminate\Routing\ControllerDispatcher->call(Object(FireflyIII\Http\Controllers\AccountController), Object(Illuminate\Routing\Route), 'destroy')
#10 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/bootstrap/cache/compiled.php(9889): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/www/bootstrap/cache/compiled.php(9413): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /var/www/bootstrap/cache/compiled.php(9400): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(FireflyIII\Http\Controllers\AccountController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'destroy')
#16 /var/www/bootstrap/cache/compiled.php(8468): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'FireflyIII\\Http...', 'destroy')
#17 /var/www/bootstrap/cache/compiled.php(8455): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#18 /var/www/bootstrap/cache/compiled.php(8169): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/www/app/Http/Middleware/Binder.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /var/www/app/Http/Middleware/Range.php(95): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /var/www/app/Http/Middleware/IsConfirmed.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: FireflyIII\Http\Middleware\IsConfirmed->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /var/www/app/Http/Middleware/AuthenticateTwoFactor.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /var/www/app/Http/Middleware/Authenticate.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /var/www/bootstrap/cache/compiled.php(3198): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /var/www/bootstrap/cache/compiled.php(13349): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/bootstrap/cache/compiled.php(11895): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /var/www/bootstrap/cache/compiled.php(13088): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 /var/www/bootstrap/cache/compiled.php(13025): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#69 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /var/www/bootstrap/cache/compiled.php(9889): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /var/www/bootstrap/cache/compiled.php(8170): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#74 /var/www/bootstrap/cache/compiled.php(8161): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#75 /var/www/bootstrap/cache/compiled.php(8151): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#76 /var/www/bootstrap/cache/compiled.php(2404): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#77 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#78 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#79 /var/www/bootstrap/cache/compiled.php(3259): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#80 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#81 /var/www/bootstrap/cache/compiled.php(9904): call_user_func_array(Array, Array)
#82 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#84 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#85 /var/www/bootstrap/cache/compiled.php(9889): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#86 /var/www/bootstrap/cache/compiled.php(2351): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#87 /var/www/bootstrap/cache/compiled.php(2335): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#88 /var/www/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#89 {main}  
```

**Comment by JC5** [comment]
It looks like I forgot to do a proper NULL check. I will fix this in the next version. Thanks for reporting!

**Comment by StevenReitsma** [comment]
Works now, thanks!
