### ISSUE TITLE
Error on composer install for version 4.0.0 (Class auth does not exist)

### ISSUE THREAD

**Issue by niekvanderkooy** [JC5/firefly-iii#332]
```
λ composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize


  [ReflectionException]
  Class auth does not exist
```

Stacktrace:
```
[2016-09-27 10:57:19] production.ERROR: ReflectionException: Class auth does not exist in E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Container\Container.php:748
Stack trace:
#0 E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Container\Container.php(748): ReflectionClass->__construct('auth')
#1 E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Container\Container.php(643): Illuminate\Container\Container->build('auth', Array)
#2 E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(709): Illuminate\Container\Container->make('auth', Array)
#3 E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(106): Illuminate\Foundation\Application->make('auth', Array)
#4 E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(147): app('Illuminate\\Cont...')
#5 E:\wamp\www\firefly\app\Exceptions\Handler.php(83): auth()
#6 E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(304): FireflyIII\Exceptions\Handler->report(Object(ErrorException))
#7 E:\wamp\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(124): Illuminate\Foundation\Console\Kernel->reportException(Object(ErrorException))
#8 E:\wamp\www\firefly\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main} 
```

**Comment by JC5** [comment]
``rm -rf vendor composer.lock``
``composer install --no-dev --no-scripts``
``php artisan cache:clear``
``composer install --no-dev``

**Comment by niekvanderkooy** [comment]
I tried `composer update`ing already, but no luck.

```
E:\wamp\www\firefly (master) Tue 27/09/2016 13:03:41.25
λ rm -rf vendor composer.lock && composer install --no-dev --no-scripts && php artisan cache:clear && composer install --no-dev
Loading composer repositories with package information
Updating dependencies
  - Installing vlucas/phpdotenv (v2.4.0)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/var-dumper (v3.1.4)
    Loading from cache

  - Installing symfony/translation (v3.1.4)
    Loading from cache

  - Installing symfony/routing (v3.1.4)
    Loading from cache

  - Installing symfony/process (v3.1.4)
    Loading from cache

  - Installing symfony/http-foundation (v3.1.4)
    Loading from cache

  - Installing symfony/event-dispatcher (v3.1.4)
    Loading from cache

  - Installing psr/log (1.0.1)
    Loading from cache

  - Installing symfony/debug (v3.1.4)
    Loading from cache

  - Installing symfony/http-kernel (v3.1.4)
    Loading from cache

  - Installing symfony/finder (v3.1.4)
    Loading from cache

  - Installing symfony/console (v3.1.4)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.4.3)
    Loading from cache

  - Installing paragonie/random_compat (v2.0.2)
    Loading from cache

  - Installing ramsey/uuid (3.5.0)
    Loading from cache

  - Installing jakub-onderka/php-console-color (0.1)
    Loading from cache

  - Installing jakub-onderka/php-console-highlighter (v0.3.2)
    Loading from cache

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Loading from cache

  - Installing nikic/php-parser (v2.1.1)
    Loading from cache

  - Installing psy/psysh (v0.7.2)
    Loading from cache

  - Installing nesbot/carbon (1.21.0)
    Loading from cache

  - Installing mtdowling/cron-expression (v1.1.0)
    Loading from cache

  - Installing monolog/monolog (1.21.0)
    Loading from cache

  - Installing league/flysystem (1.0.27)
    Loading from cache

  - Installing symfony/polyfill-util (v1.2.0)
    Loading from cache

  - Installing symfony/polyfill-php56 (v1.2.0)
    Loading from cache

  - Installing jeremeamia/superclosure (2.2.0)
    Loading from cache

  - Installing doctrine/inflector (v1.1.0)
    Loading from cache

  - Installing classpreloader/classpreloader (3.0.0)
    Loading from cache

  - Installing laravel/framework (v5.3.10)
    Loading from cache

  - Installing watson/validating (3.0.0)
    Loading from cache

  - Installing league/commonmark (0.15.0)
    Loading from cache

  - Installing twig/twig (v1.25.0)
    Loading from cache

  - Installing rcrowe/twigbridge (v0.9.3)
    Loading from cache

  - Installing laravelcollective/html (v5.3.0)
    Loading from cache

  - Installing davejamesmiller/laravel-breadcrumbs (3.0.1)
    Loading from cache

  - Installing doctrine/lexer (v1.0.1)
    Loading from cache

  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing doctrine/cache (v1.6.0)
    Loading from cache

  - Installing doctrine/annotations (v1.2.7)
    Loading from cache

  - Installing doctrine/common (v2.6.1)
    Loading from cache

  - Installing doctrine/dbal (v2.5.5)
    Loading from cache

  - Installing league/csv (8.1.1)
    Loading from cache

  - Installing rmccue/requests (v1.6.1)
    Loading from cache

  - Installing christian-riesen/base32 (1.3.1)
    Loading from cache

  - Installing pragmarx/google2fa (v1.0.1)
    Loading from cache

  - Installing maximebf/debugbar (v1.13.0)
    Loading from cache

  - Installing barryvdh/laravel-debugbar (v2.3.0)
    Loading from cache

  - Installing symfony/class-loader (v3.1.4)
    Loading from cache

  - Installing barryvdh/reflection-docblock (v2.0.4)
    Loading from cache

  - Installing barryvdh/laravel-ide-helper (v2.2.1)
    Loading from cache

  - Installing bacon/bacon-qr-code (1.0.1)
    Loading from cache

Writing lock file
Generating autoload files


  [ReflectionException]
  Class auth does not exist


Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize


  [ReflectionException]
  Class auth does not exist
```

**Comment by JC5** [comment]
I've had this a few times, I just can't remember what I did to fix it. Aren't there some files in bootstrap/ that are not in Git? If so, remove them.

**Comment by niekvanderkooy** [comment]
Nope, only things in there are app.php and autoload.php

**Comment by JC5** [comment]
Delete bootstrap/cache/services.php

**Comment by niekvanderkooy** [comment]
I had already done that. Nothing in bootstrap except `app.php` and `autoload.php` - no folders either.

**Comment by JC5** [comment]
My default dev-machine can re-install Firefly III without any problems. Fresh checkout in a fresh directory. Tonight, I'll build a new machine and try it again.

**Comment by niekvanderkooy** [comment]
A fresh install worked for me as well. Doesn't explain what went wrong in the upgrade, but at least it's not a persistent problem.

**Comment by JC5** [comment]
Good! I'll see what I can find. Maybe a cache thing? I'm closing it for now.
