### ISSUE TITLE
Rules match all transactions

### ISSUE THREAD

**Issue by marcoveeneman** [JC5/firefly-iii#333]
I'm trying to organize my transactions into some categories. I found the option to trigger rules on already existing transactions but for some reason it is not working for me.

When i check the trigger to see matching transactions it shows some correct transactions but when i finally execute the trigger group all of my transactions are added to the category. Example:

The rule triggers on `Destination account contains..` : `Lidl`. The rule will `Set category to..` : `Groceries`.

The above rule matches 2 transactions. When i execute this on existing transactions all transactions are added to the `Groceries` categorie, no matter if the rule trigger matches or not :(

I'm currently running Firefly iii 3.10.4. I checked the changes since then but couldn't find a fix for this yet so i guess this is still present in 4.0.0.

**Comment by JC5** [comment]
There's a lot of debug information, so the logs should give you some hints as to why rules are a hit or a miss. Check out your ``.env`` file and be sure the log level is DEBUG.

Where exactly did you find the option to re-apply rules? There is a test button, not a re-apply button, as far as I know.

**Comment by marcoveeneman** [comment]
I found the re-apply button here:
![image](https://cloud.githubusercontent.com/assets/4264614/18888759/fb62e0d2-84f9-11e6-96cf-cf09d0a76361.png)

Ok i enabled the debug log level and it indeed matches,

```
[2016-09-27 19:27:43] production.DEBUG: start of Processor::triggered()  
[2016-09-27 19:27:43] production.DEBUG: Now checking trigger FireflyIII\Rules\Triggers\ToAccountContains with value Lidl  
[2016-09-27 19:27:43] production.DEBUG: Now checking trigger FireflyIII\Rules\Triggers\UserAction with value store-journal  
[2016-09-27 19:27:43] production.DEBUG: Is a match!  
[2016-09-27 19:27:43] production.DEBUG: Result of triggered() {"hitTriggers":1,"foundTriggers":1,"result":true}
```

But why does it match on `store-journal`?

My rule is looking like this:
![image](https://cloud.githubusercontent.com/assets/4264614/18888809/31136c92-84fa-11e6-9a0f-c422d4cfc404.png)

**Comment by JC5** [comment]
Lol I forgot about that button. Pretty sure I told people there's no such
thing.

I'll make sure that it's more visible for a start.

The store journal trigger always fires in these situations, otherwise the
reapply button could not even work. But I see nothing negative feedback
from your Lidl trigger which [the code](
https://github.com/JC5/firefly-iii/blob/master/app/Rules/Triggers/ToAccountContains.php)
contains in the next version.

Hold on off the upgrade until I close #332, then upgrade and at least we
can take a close look at what Firefly is doing.

**Comment by JC5** [comment]
Lol I forgot about that button. Pretty sure I told people there's no such thing.

I'll make sure that it's more visible for a start.

The store journal trigger always fires in these situations, otherwise the reapply button could not even work. But I see nothing negative feedback from your Lidl trigger which [the code](https://github.com/JC5/firefly-iii/blob/master/app/Rules/Triggers/ToAccountContains.php) contains in the next version.

Hold on off the upgrade until I close #332, then upgrade and at least we can take a close look at what Firefly is doing.

**Comment by JC5** [comment]
Alright, #332 is closed, let me know what happens here. I'll see if I can reproduce it.

**Comment by marcoveeneman** [comment]
Thanks, i just updated to 4.0.0 and got the following  exception while removing an existing category:
```
[2016-10-03 19:59:10] production.ERROR: UnexpectedValueException: The Response content must be a string or object implementing __toString(), "object" given. in C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php:16029
Stack trace:
#0 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(16445): Symfony\Component\HttpFoundation\Response->setContent(Object(Illuminate\Routing\Redirector))
#1 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(15930): Illuminate\Http\Response->setContent(Object(Illuminate\Routing\Redirector))
#2 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8290): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Routing\Redirector))
#3 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8123): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Redirector))
#4 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 C:\wamp64\www\firefly-iii\app\Http\Middleware\Binder.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\wamp64\www\firefly-iii\app\Http\Middleware\Range.php(78): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\wamp64\www\firefly-iii\app\Http\Middleware\IsConfirmed.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\IsConfirmed->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 C:\wamp64\www\firefly-iii\app\Http\Middleware\AuthenticateTwoFactor.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\wamp64\www\firefly-iii\app\Http\Middleware\Authenticate.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9954): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(3127): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13439): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(11883): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13185): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13122): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9831): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8124): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8115): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#41 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8106): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#42 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2452): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#43 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#44 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(3189): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9831): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2396): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2380): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#50 C:\wamp64\www\firefly-iii\public\index.php(62): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#51 {main}  
```
Also, creating a new rule gave the following exception:
```
[2016-10-03 20:03:23] production.ERROR: UnexpectedValueException: The Response content must be a string or object implementing __toString(), "object" given. in C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php:16029
Stack trace:
#0 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(16445): Symfony\Component\HttpFoundation\Response->setContent(Object(Illuminate\Routing\Redirector))
#1 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(15930): Illuminate\Http\Response->setContent(Object(Illuminate\Routing\Redirector))
#2 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8290): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Routing\Redirector))
#3 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8123): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Redirector))
#4 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 C:\wamp64\www\firefly-iii\app\Http\Middleware\Binder.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\wamp64\www\firefly-iii\app\Http\Middleware\Range.php(78): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\wamp64\www\firefly-iii\app\Http\Middleware\IsConfirmed.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\IsConfirmed->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 C:\wamp64\www\firefly-iii\app\Http\Middleware\AuthenticateTwoFactor.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\wamp64\www\firefly-iii\app\Http\Middleware\Authenticate.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9954): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(3127): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13439): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(11883): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13185): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13122): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9831): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8124): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8115): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#41 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8106): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#42 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2452): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#43 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#44 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(3189): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9846): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9831): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2396): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2380): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#50 C:\wamp64\www\firefly-iii\public\index.php(62): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#51 {main}  
```

After both the exceptions, the 'whoops something went wrong' page was shown but the removal of the group and creation of the rule succeeded.

**Comment by marcoveeneman** [comment]
Ok this is rea;ly strange, I just executed the new rule group and it seems to work now. Let me do some more tests to verify everything works as expected.

**Comment by JC5** [comment]
Could be cache-related.

**Comment by applelam** [comment]
I have experienced the same issue after I upgraded from 3.8.x to 3.10.x.
Upgrading to 4.0.0 solve this problem.

**Comment by JC5** [comment]
Alright, I'm closing this one. Let me know if something breaks!
