### ISSUE TITLE
'There is no user present' error when importing from command line

### ISSUE THREAD

**Issue by roberthorlings** [JC5/firefly-iii#338]
I'm trying to import a file into firefly from the command line (using version 3.10.4). However, I keep on getting an error stating 'There is no user present'. I would suspect this has something to with a rule being applied to assign a budget to a newly imported transaction.

Is there a way to circumvent this problem?

```
Going to import job with key "YjZm2qOldVZr" of type csv
[2016-09-29 14:20:11] production.NOTICE: Building importable objects from CSV file. [] []
[2016-09-29 14:20:12] production.NOTICE: Built 111 importable object(s) from your CSV file. [] []
[2016-09-29 14:20:12] production.NOTICE: Started validating 111 entry(ies). [] []
[2016-09-29 14:20:18] production.NOTICE: Finished validating 111 entry(ies). [] []
[2016-09-29 14:20:18] production.NOTICE: Started storing 111 entry(ies). [] []
[2016-09-29 14:20:18] production.WARNING: Cannot import row 1, because it has already been imported (journal #3557). [] []
[2016-09-29 14:20:18] production.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"There is no user present.","time":"Thu, 29 Sep 2016 14:20:18 +0000","file":"\/home\/robert\/tools\/firefly-3.10.4\/app\/Providers\/BudgetServiceProvider.php","line":50,"code":0} [] []
[2016-09-29 14:20:19] production.ERROR: FireflyIII\Exceptions\FireflyException: There is no user present. in /home/robert/tools/firefly-3.10.4/app/Providers/BudgetServiceProvider.php:50 Stack trace: #0 /home/robert/tools/firefly-3.10.4/bootstrap/cache/compiled.php(1353): FireflyIII\Providers\BudgetServiceProvider->FireflyIII\Providers\{closure}(Object(Illuminate\Foundation\Application), Array) #1 /home/robert/tools/firefly-3.10.4/bootstrap/cache/compiled.php(1309): Illuminate\Container\Container->build(Object(Closure), Array) #2 /home/robert/tools/firefly-3.10.4/bootstrap/cache/compiled.php(1874): Illuminate\Container\Container->make('FireflyIII\\Repo...', Array) #3 /home/robert/tools/firefly-3.10.4/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Illuminate\Foundation\Application->make('FireflyIII\\Repo...', Array) #4 /home/robert/tools/firefly-3.10.4/app/Rules/Actions/SetBudget.php(49): app('FireflyIII\\Repo...') #5 /home/robert/tools/firefly-3.10.4/app/Rules/Processor.php(190): FireflyIII\Rules\Actions\SetBudget->act(Object(FireflyIII\Models\TransactionJournal)) #6 /home/robert/tools/firefly-3.10.4/app/Rules/Processor.php(168): FireflyIII\Rules\Processor->actions() #7 /home/robert/tools/firefly-3.10.4/app/Import/ImportStorage.php(139): FireflyIII\Rules\Processor->handleTransactionJournal(Object(FireflyIII\Models\TransactionJournal)) #8 /home/robert/tools/firefly-3.10.4/app/Import/ImportStorage.php(96): FireflyIII\Import\ImportStorage->applyRules(Object(FireflyIII\Models\TransactionJournal)) #9 /home/robert/tools/firefly-3.10.4/app/Import/ImportProcedure.php(68): FireflyIII\Import\ImportStorage->store() #10 /home/robert/tools/firefly-3.10.4/app/Console/Commands/Import.php(70): FireflyIII\Import\ImportProcedure::runImport(Object(FireflyIII\Models\ImportJob)) #11 [internal function]: FireflyIII\Console\Commands\Import->handle() #12 /home/robert/tools/firefly-3.10.4/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array) #13 /home/robert/tools/firefly-3.10.4/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array) #14 /home/robert/tools/firefly-3.10.4/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /home/robert/tools/firefly-3.10.4/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /home/robert/tools/firefly-3.10.4/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /home/robert/tools/firefly-3.10.4/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\Import), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /home/robert/tools/firefly-3.10.4/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 /home/robert/tools/firefly-3.10.4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 /home/robert/tools/firefly-3.10.4/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #21 {main} [] []

                                            
  [FireflyIII\Exceptions\FireflyException]  
  There is no user present.                                                             
```

**Comment by JC5** [comment]
Fixed, will be released this weekend!
