### ISSUE TITLE
Some pages are broken when using PostgreSQL

### ISSUE THREAD

**Issue by SanderKleykens** [JC5/firefly-iii#346]
In Firefly v4.0.1, "/accounts/asset" and "accounts/expense" (and possibly other pages) seem to be broken when using PostgreSQL. 
You get a "Whoops, looks like something went wrong.".

The logs contain the following:
```
Next Illuminate\Database\QueryException: SQLSTATE[42601]: Syntax error: 7 ERROR:
  syntax error at or near "."
LINE 1: ...ct "transactions"."account_id", sum(`transactions`.`amount`)...
                                                             ^ (SQL: select "tra
nsactions"."account_id", sum(`transactions`.`amount`) as aggregate from "transac
tions" left join "transaction_journals" on "transaction_journals"."id" = "transa
ctions"."transaction_journal_id" where "transaction_journals"."date" <= 2016-09-
30 and 0 = 1 and "transactions"."deleted_at" is null group by "transactions"."ac
count_id") in /opt/firefly/vendor/laravel/framework/src/Illuminate/Database/Conn
ection.php:761
Stack trace:
#0 /opt/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(
717): Illuminate\Database\Connection->runQueryCallback('select "transac...', Arr
ay, Object(Closure))
#1 /opt/firefly/vendor/laravel/framework/src/Illuminate/Database/Connection.php(
351): Illuminate\Database\Connection->run('select "transac...', Array, Object(Cl
osure))
#2 /opt/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.p
hp(1648): Illuminate\Database\Connection->select('select "transac...', Array, tr
ue)
#3 /opt/firefly/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.p
hp(1634): Illuminate\Database\Query\Builder->runSelect()
#4 /opt/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builde
r.php(613): Illuminate\Database\Query\Builder->get(Array)
#5 /opt/firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builde
r.php(318): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /opt/firefly/app/Support/Steam.php(165): Illuminate\Database\Eloquent\Builder
->get(Array)
#7 /opt/firefly/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.p
hp(237): FireflyIII\Support\Steam->balancesById(Array, Object(Carbon\Carbon))
#8 /opt/firefly/app/Http/Controllers/AccountController.php(181): Illuminate\Supp
ort\Facades\Facade::__callStatic('balancesById', Array)
#9 [internal function]: FireflyIII\Http\Controllers\AccountController->index(Obj
ect(FireflyIII\Crud\Account\AccountCrud), 'expense')
#10 /opt/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(
55): call_user_func_array(Array, Array)
#11 /opt/firefly/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispa
tcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
.
.
.
#54 /opt/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53
): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Objec
t(Illuminate\Http\Request))
#55 /opt/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middlew
are/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Rou
ting\{closure}(Object(Illuminate\Http\Request))
#56 /opt/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(1
37): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Objec
t(Illuminate\Http\Request), Object(Closure))
#57 /opt/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33
): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate
\Http\Request))
#58 /opt/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(1
04): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate
\Http\Request))
#59 /opt/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.
php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /opt/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.
php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Ill
uminate\Http\Request))
#61 /opt/firefly/public/index.php(62): Illuminate\Foundation\Http\Kernel->handle
(Object(Illuminate\Http\Request))
#62 {main}
```

**Comment by JC5** [comment]
Ah yes, that's because I've been using mysql specific dialectic in some cases. Most queries haven't got this problem but one or two.. I'll look for it and fix it.

**Comment by SanderKleykens** [comment]
Thanks for the quick fix, @JC5!

I stumbled upon some other issues (related to the use of XOR in SQL queries). I have opened pull request #348 with my fixes.
