### ISSUE TITLE
Upgrade error to 4.01

### ISSUE THREAD

**Issue by xzaz** [JC5/firefly-iii#347]
``root@webserver01:/firefly-iii# php artisan migrate --env=production
PHP Fatal error:  Uncaught ReflectionException: Class auth does not exist in /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('auth')
#1 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('auth', Array)
#2 /firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('auth', Array)
#3 /firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Illuminate\Foundation\Application->make('auth', Array)
#4 /firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.p in /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
PHP Fatal error:  Uncaught ReflectionException: Class auth does not exist in /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('auth')
#1 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('auth', Array)
#2 /firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('auth', Array)
#3 /firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Illuminate\Foundation\Application->make('auth', Array)
#4 /firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.p in /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734``

**Comment by xzaz** [comment]
Alternative Upgrade fixed it.
