### ISSUE TITLE
"Could not decrypt preference #11" error after registration on fresh database in develop branch

### ISSUE THREAD

**Issue by roberthorlings** [JC5/firefly-iii#353]
An error occurred after registering in the develop branch on a fresh database:
```
Could not decrypt preference #11.

Error

This error occured in file /home/robert/projects/isdat/firefly/firefly-iii/app/Models/Preference.php on line 61 with code 0.

Stack trace

#0 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2722): FireflyIII\Models\Preference->getDataAttribute('')
#1 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2624): Illuminate\Database\Eloquent\Model->mutateAttribute('data', '')
#2 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2600): Illuminate\Database\Eloquent\Model->getAttributeValue('data')
#3 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3423): Illuminate\Database\Eloquent\Model->getAttribute('data')
#4 /home/robert/projects/isdat/firefly/firefly-iii/app/Http/Middleware/AuthenticateTwoFactor.php(56): Illuminate\Database\Eloquent\Model->__get('data')
#5 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 /home/robert/projects/isdat/firefly/firefly-iii/app/Http/Middleware/Authenticate.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#9 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/robert/projects/isdat/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
```

**Comment by JC5** [comment]
Possibly a cache issue, if the database was fresh but the installation was untouched. The old value might still be in the cache.

Run ``php artisan cache:clear`` on the command line and you should be fine.

**Comment by roberthorlings** [comment]
Great, that works fine! Thanks
