### ISSUE TITLE
Unable to login due to Google2FA exception after update

### ISSUE THREAD

**Issue by ksmolder** [JC5/firefly-iii#360]
I updated my installation of firefly-iii today via `composer update`. After the update, I was unable to login again (2FA is enabled for the account). The log reads:

```
[2016-10-21 22:57:44] production.ERROR: PragmaRX\Google2FA\Exceptions\InvalidCharactersException: Invalid characters in the base32 string. in /var/www/firefly-iii/vendor/pragmarx/google2fa/src/Google2FA.php:289
Stack trace:
#0 /var/www/firefly-iii/vendor/pragmarx/google2fa/src/Google2FA.php(104): PragmaRX\Google2FA\Google2FA->validateSecret('')
#1 /var/www/firefly-iii/vendor/pragmarx/google2fa/src/Google2FA.php(172): PragmaRX\Google2FA\Google2FA->base32Decode('')
#2 /var/www/firefly-iii/bootstrap/cache/compiled.php(6295): PragmaRX\Google2FA\Google2FA->verifyKey(NULL, '355798')
#3 /var/www/firefly-iii/app/Validation/FireflyValidator.php(70): Illuminate\Support\Facades\Facade::__callStatic('verifyKey', Array)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(557): FireflyIII\Validation\FireflyValidator->validate2faCode('code', '355798', Array, Object(FireflyIII\Validation\FireflyValidator))
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(471): Illuminate\Validation\Validator->validateAttribute('code', '2faCode')
#6 /var/www/firefly-iii/bootstrap/cache/compiled.php(5449): Illuminate\Validation\Validator->passes()
#7 /var/www/firefly-iii/bootstrap/cache/compiled.php(5656): Illuminate\Foundation\Http\FormRequest->validate()
#8 /var/www/firefly-iii/bootstrap/cache/compiled.php(1515): Illuminate\Foundation\Providers\FoundationServiceProvider->Illuminate\Foundation\Providers\{closure}(Object(FireflyIII\Http\Requests\TokenFormRequest), Object(Illuminate\Foundation\Application))
#9 /var/www/firefly-iii/bootstrap/cache/compiled.php(1500): Illuminate\Container\Container->fireCallbackArray(Object(FireflyIII\Http\Requests\TokenFormRequest), Array)
#10 /var/www/firefly-iii/bootstrap/cache/compiled.php(1340): Illuminate\Container\Container->fireResolvingCallbacks('FireflyIII\\Http...', Object(FireflyIII\Http\Requests\TokenFormRequest))
#11 /var/www/firefly-iii/bootstrap/cache/compiled.php(1908): Illuminate\Container\Container->make('FireflyIII\\Http...', Array)
#12 /var/www/firefly-iii/bootstrap/cache/compiled.php(7894): Illuminate\Foundation\Application->make('FireflyIII\\Http...')
#13 /var/www/firefly-iii/bootstrap/cache/compiled.php(7883): Illuminate\Routing\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array, Array)
#14 /var/www/firefly-iii/bootstrap/cache/compiled.php(7877): Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
#15 /var/www/firefly-iii/bootstrap/cache/compiled.php(9399): Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(FireflyIII\Http\Controllers\Auth\TwoFactorController), 'postIndex')
#16 /var/www/firefly-iii/bootstrap/cache/compiled.php(8459): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Auth\TwoFactorController), 'postIndex')
#17 /var/www/firefly-iii/bootstrap/cache/compiled.php(8440): Illuminate\Routing\Route->runController()
#18 /var/www/firefly-iii/bootstrap/cache/compiled.php(8149): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/firefly-iii/app/Http/Middleware/RedirectIfTwoFactorAuthenticated.php(47): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): FireflyIII\Http\Middleware\RedirectIfTwoFactorAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/firefly-iii/bootstrap/cache/compiled.php(9967): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/firefly-iii/bootstrap/cache/compiled.php(3151): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/firefly-iii/bootstrap/cache/compiled.php(13205): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/firefly-iii/bootstrap/cache/compiled.php(13142): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/firefly-iii/bootstrap/cache/compiled.php(9967): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/firefly-iii/bootstrap/cache/compiled.php(13459): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/firefly-iii/bootstrap/cache/compiled.php(3151): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/firefly-iii/bootstrap/cache/compiled.php(13459): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/firefly-iii/bootstrap/cache/compiled.php(11899): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/firefly-iii/bootstrap/cache/compiled.php(11899): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/firefly-iii/bootstrap/cache/compiled.php(13205): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/firefly-iii/bootstrap/cache/compiled.php(13142): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/firefly-iii/bootstrap/cache/compiled.php(9844): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/firefly-iii/bootstrap/cache/compiled.php(8150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/firefly-iii/bootstrap/cache/compiled.php(8141): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#65 /var/www/firefly-iii/bootstrap/cache/compiled.php(8132): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#66 /var/www/firefly-iii/bootstrap/cache/compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#67 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/firefly-iii/bootstrap/cache/compiled.php(3213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/firefly-iii/bootstrap/cache/compiled.php(9859): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /var/www/firefly-iii/bootstrap/cache/compiled.php(9844): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /var/www/firefly-iii/bootstrap/cache/compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#73 /var/www/firefly-iii/bootstrap/cache/compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#74 /var/www/firefly-iii/public/index.php(62): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#75 {main}  
```

I tried to replace the updated installation with a backup copy, but then I get an error about saying Auth class is not found:

```
2016-10-21 23:03:47] production.ERROR: ReflectionException: Class auth does not exist in /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:748
Stack trace:
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(748): ReflectionClass->__construct('auth')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(643): Illuminate\Container\Container->build('auth', Array)
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('auth', Array)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(106): Illuminate\Foundation\Application->make('auth', Array)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(147): app('Illuminate\\Cont...')
#5 /var/www/firefly-iii/app/Exceptions/Handler.php(83): auth()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(300): FireflyIII\Exceptions\Handler->report(Object(ErrorException))
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\Foundation\Http\Kernel->reportException(Object(ErrorException))
#8 /var/www/firefly-iii/public/index.php(62): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#9 {main}  
```

Is there anything I can do to login into my account again? Can I somehow disable 2FA for this account?

**Comment by JC5** [comment]
Try to run the following:

``php artisan cache:clear``

Then, visit your site again. If that does not work, access your database and find the table ``preferences``.

Search for the entries with names ``twoFactorAuthEnabled`` and ``twoFactorAuthSecret`` and remove them. 

Then, run ``php artisan cache:clear`` again.

That should disable 2FA. Make sure you delete the account from your Authenticator app as well.

The problem might be cache related, so I hope the first trick should already work.

**Comment by ksmolder** [comment]
Cleaning the cache helped! Thanks for the fast feedback!
