### ISSUE TITLE
Mass edit transactions generates error

### ISSUE THREAD

**Issue by marcoveeneman** [JC5/firefly-iii#401]
Hi,

I'm trying to edit multiple transactions (income/revenue) simultaneously but firefly throws an error when i press the 'Update these transactions' Button with the following error:

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:

Undefined index: currency_id
```
And the stack trace:
```
[2016-11-11 19:08:13] production.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Undefined index: currency_id","time":"Fri, 11 Nov 2016 19:08:13 +0000","file":"C:\\wamp64\\www\\firefly-iii\\app\\Repositories\\Journal\\JournalRepository.php","line":249,"code":0}  
[2016-11-11 19:08:23] production.ERROR: ErrorException: Undefined index: currency_id in C:\wamp64\www\firefly-iii\app\Repositories\Journal\JournalRepository.php:249
Stack trace:
#0 C:\wamp64\www\firefly-iii\app\Repositories\Journal\JournalRepository.php(249): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', 'C:\\wamp64\\www\\f...', 249, Array)
#1 C:\wamp64\www\firefly-iii\app\Http\Controllers\Transaction\MassController.php(231): FireflyIII\Repositories\Journal\JournalRepository->update(Object(FireflyIII\Models\TransactionJournal), Array)
#2 [internal function]: FireflyIII\Http\Controllers\Transaction\MassController->massUpdate(Object(FireflyIII\Http\Requests\MassEditJournalRequest), Object(FireflyIII\Repositories\Journal\JournalRepository))
#3 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9389): call_user_func_array(Array, Array)
#4 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9416): Illuminate\Routing\Controller->callAction('massUpdate', Array)
#5 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8474): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Transaction\MassController), 'massUpdate')
#6 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8455): Illuminate\Routing\Route->runController()
#7 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8151): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\wamp64\www\firefly-iii\app\Http\Controllers\Transaction\MassController.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9866): FireflyIII\Http\Controllers\Transaction\MassController->FireflyIII\Http\Controllers\Transaction\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#11 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 C:\wamp64\www\firefly-iii\app\Http\Controllers\Controller.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9866): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\wamp64\www\firefly-iii\app\Http\Middleware\Binder.php(55): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\wamp64\www\firefly-iii\app\Http\Middleware\Range.php(83): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\wamp64\www\firefly-iii\app\Http\Middleware\IsConfirmed.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): FireflyIII\Http\Middleware\IsConfirmed->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\wamp64\www\firefly-iii\app\Http\Middleware\AuthenticateTwoFactor.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\wamp64\www\firefly-iii\app\Http\Middleware\Authenticate.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9982): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(3151): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13471): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(11911): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13217): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(13154): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9859): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8152): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8143): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#51 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(8134): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#52 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#53 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#54 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(3213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9874): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 C:\wamp64\www\firefly-iii\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(9859): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 C:\wamp64\www\firefly-iii\bootstrap\cache\compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#60 C:\wamp64\www\firefly-iii\public\index.php(62): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#61 {main}  
```

**Comment by JC5** [comment]
Confirmed and fixed :)
